title: El Mundo De Shaina!
description: Hola, soy Shaina (la autora del Blog), y os os mantendre actualizados sobre la comida y la injustica de este mundo...
permalink: ':title/'
baseurl: "/" 
url: "https://canvas2017.github.io" 
site-twitter: 


author: El Mundo De Shaina! 
author-img: logo-pie.png  
about-author: Bienvenidos a mi mundo!!!! Por si no ha quedado claro, mi nombre es Shaina (ni china, ni shainy) y si te gusta el chocolate o/y leer sobre la injusticia de este mundo, has visitado el lugar perfecto!
social-twitter: 
social-facebook: 
social-github: 
social-linkedin: 
social-email: 




# Disqus
discus-identifier:  

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
